### ISSUE TITLE
Getting Error " java.lang.NullPointerException"

### ISSUE THREAD

**Issue by pranavlathigara** [txusballesteros/bubbles-for-android#2]
java.lang.NullPointerException
            at android.animation.PropertyValuesHolder.setupSetterAndGetter(PropertyValuesHolder.java:505)
            at android.animation.ObjectAnimator.initAnimation(ObjectAnimator.java:487)
            at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:517)
            at android.animation.ValueAnimator.start(ValueAnimator.java:936)
            at android.animation.ValueAnimator.start(ValueAnimator.java:946)
            at android.animation.ObjectAnimator.start(ObjectAnimator.java:465)
            at android.animation.AnimatorSet.start(AnimatorSet.java:563)
            at com.txusballesteros.bubbles.BubbleTrashLayout.playAnimation(BubbleTrashLayout.java:78)
            at com.txusballesteros.bubbles.BubbleTrashLayout.setVisibility(BubbleTrashLayout.java:54)
            at com.txusballesteros.bubbles.BubblesService.addTrash(BubblesService.java:102)
            at com.txusballesteros.bubbles.BubblesManager.configureBubblesService(BubblesManager.java:67)
            at com.txusballesteros.bubbles.BubblesManager.access$100(BubblesManager.java:33)
            at com.txusballesteros.bubbles.BubblesManager$1.onServiceConnected(BubblesManager.java:52)
            at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1110)
            at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1127)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:149)
            at android.app.ActivityThread.main(ActivityThread.java:5257)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by txusballesteros** [comment]
Hi @pranavlathigara,

I will need more info about your environment, because I cannot capture and reproduce your exception with my demo App.

Thx

**Comment by txusballesteros** [comment]
@pranavlathigara I have written defensive code to prevent your crash, please, can you confirm that the issue has been solved?

**Comment by luizfp** [comment]
@txusballesteros What was your solution?
