### ISSUE TITLE
Facing Crash whne I remove BubbleView

### ISSUE THREAD

**Issue by monishagarwal215** [txusballesteros/bubbles-for-android#27]
Process: com.lookatme, PID: 462
                                                          java.lang.IllegalArgumentException: View=com.txusballesteros.bubbles.BubbleLayout{24789439 V.E...C. ......I. 0,0-0,0} not attached to window manager
                                                              at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:416)
                                                              at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:342)
                                                              at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:111)
                                                              at com.txusballesteros.bubbles.BubblesService$1.run(BubblesService.java:69)
                                                              at android.os.Handler.handleCallback(Handler.java:815)
                                                              at android.os.Handler.dispatchMessage(Handler.java:104)
                                                              at android.os.Looper.loop(Looper.java:194)
                                                              at android.app.ActivityThread.main(ActivityThread.java:5637)
                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

**Comment by prgpascal** [comment]
I got the same error :( how to solve this?

**Comment by sathish5131** [comment]
same error
