### ISSUE TITLE
How can I set transparency, size via seekbar?

### ISSUE THREAD

**Issue by coolamz** [txusballesteros/bubbles-for-android#37]
I'm trying to set transparency and change size via seekbar. But I'm getting this error. Please tell me how can I do that? Following error I get after using setAlpha.

E/UncaughtException: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setAlpha(float)' on a null object reference
                         at com.amey.voicebutton.Main2Activity$6.onClick(Main2Activity.java:155)
                         at android.view.View.performClick(View.java:5610)
                         at android.view.View$PerformClick.run(View.java:22265)
                         at android.os.Handler.handleCallback(Handler.java:751)
                         at android.os.Handler.dispatchMessage(Handler.java:95)
                         at android.os.Looper.loop(Looper.java:154)
                         at android.app.ActivityThread.main(ActivityThread.java:6077)
                         at java.lang.reflect.Method.invoke(Native Method)
                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
I/FA: Tag Manager is not found and thus will not be used
D/FA: Logging event (FE): _ae, Bundle[{_o=crash, _sc=Main2Activity, _si=-3901322298145191894, timestamp=1487272019047, fatal=1}]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.amey.voicebutton, PID: 5834
                  java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setAlpha(float)' on a null object reference
                      at com.amey.voicebutton.Main2Activity$6.onClick(Main2Activity.java:155)
                      at android.view.View.performClick(View.java:5610)
                      at android.view.View$PerformClick.run(View.java:22265)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by coolamz** [comment]
I was able to change transparency by setting up alpha directly to bubbleview like this in my onprogresschanged of seekbar.

 @Override
            public void onProgressChanged(SeekBar seekBar, int i, boolean b) {
                float f= 1-(float)i/10;
                bubbleView.setAlpha(f);
            }

 But still, I'm unable to change the size. Since, ImageView is not visible.
